server:
  port: 0             # Port par défaut du serveur

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mokengeli_biloko_db
    username: user1
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 180000       # 3 minutes
      connection-timeout: 30000
      leak-detection-threshold: 60000
  jpa:
    properties:
      hibernate:
        default_schema: order_schema
        jdbc:
          time_zone: Europe/Paris

  jackson:
    time-zone: Europe/Paris


security:
  cors:
    allowed-origins: http://localhost:3000
  jwt:
    secret: 9a4f2c_8d3b7a1e6f#45c8a0b3f268b1d4e6-f3c8a9d2b5f8e3a9c8-b5f6v8a3d9A@
  is-ssl: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL du serveur Eureka
    fetch-registry: true  # Le client doit récupérer les services
    register-with-eureka: true  # Le client s'enregistre dans le registre
  instance:
    prefer-ip-address: true  # Utilise l'adresse IP pour l'enregistrement (utile pour les environnements containerisés)
    metadata-map:
      socketio-port: ${socketio.port}

management:
  endpoint:
    websocket:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics, websocket
user:
  service-id: user-service
inventory:
  service-id: inventory-service
logging:
  level:
    com.zaxxer.hikari: INFO
    com.bacos.mokengeli.biloko: INFO

socketio:
  port: 9092

